version: 2
root-markers:
  - .git/

tools:
  javascript-eslint: &javascript-eslint
    lint-command: 'eslint -f unix --stdin'
    lint-ignore-exit-code: true
    lint-stdin: true

languages:
  javascript:
    - <<: *javascript-eslint
  javascriptreact:
    - <<: *javascript-eslint
