# disable starship from forcing a new line to be taken. Solved the empty line 
# at start of terminal
add_newline = false

[line_break]
disabled = false

[aws]
disabled = true
symbol = " "

[battery]
full_symbol = ""
charging_symbol = ""
discharging_symbol = ""

[directory]
read_only = " "

[docker]
symbol = " "

[elixir]
symbol = " "

[git_branch]
symbol = " "

[haskell]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[memory_usage]
symbol = " "

[nodejs]
symbol = " "

[package]
disabled = true
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

[cmd_duration]
min_time = 3
show_milliseconds = false
format = "  [$duration]($style) "
